### ISSUE TITLE
Error: "The application was unable to start correctly"

### ISSUE THREAD

**Issue by RustyToad** [SuslikV/untrunc-w#10]
Hi, I'm trying to run this but I'm having trouble. I've downloaded the dependencies and tried with both the "originally used" and the "latest"  versions. I had to manually download msvcp120.dll too, and put it in the same folder. I've tried both 32 and 64 bit versions. I tried to install the Microsoft visual C++ Redistributable package, but the installers (both 32 and 64 bit) are exiting silently without doing anything on my computer.

The error message reads "The application was unable to start correctly (0xc000007b). Click OK to close the application." Screenshot [here](https://i.imgur.com/9Q49jZc.png).

I'm running Windows 7. It has Symantic AV installed (cannot disable it), but I have unblocked untrunc so I don't think this is causing the problem.

At this stage I don't know if it is my setup, or a problem with untrunc. Thanks.

**Comment by SuslikV** [comment]
There is .7z version or "untrunc-w32.7z" (in [releases](https://github.com/SuslikV/untrunc-w/releases)) that is bundled with the required libraries.
Also, make sure that application placed in the folder that you can access (like "C:\temp").
The required vc++ 2013 is x86 only (should be already installed if you compile application manually using VS2013). Just for linking.

And check CRC of the .exe file after it downloaded (or unpacked in case of .7z version). The right checksum is under the releases info.
