### ISSUE TITLE
Can not open workingfile.mp4

### ISSUE THREAD

**Issue by McSkilly** [SuslikV/untrunc-w#15]
![recovery_failed](https://user-images.githubusercontent.com/41761989/46451943-bb6aec00-c75e-11e8-9f18-44b5982f91ec.png)

I'm not sure what is going wrong, but the script can not open my working mp4 file for some reason (it's not corrupted in any way)

**Comment by McSkilly** [comment]
I figured it out. I had to use workingfile.mp4.mp4 and brokenfile.mp4.mp4. It's currently working its magic; I'll let you know the results!

**Comment by SuslikV** [comment]
Quite strange naming for files (double extension, I mean). And the desktop folder is not the best place for the recovery. The process will attempt to copy almost whole broken file content during recovery, and thus, you may run out of disk space.

**Comment by McSkilly** [comment]
Yes, I fixed the file names now and I did indeed run out of disk space. Am I able to run this on another drive, or must it be on my main drive?

**Comment by SuslikV** [comment]
Any drive, any path (full path, if you wish).

**Comment by McSkilly** [comment]
Thank you, I will run it again on a drive with more space.

**Comment by SuslikV** [comment]
What %% you got  recovered before you run out of space?

**Comment by McSkilly** [comment]
I don't remember what it was, but I ran out of space on the "copying 'mdat' box..." stage before

**Comment by McSkilly** [comment]
Okay, the file was successfully recovered now and I can play it. Is it normal for it to be at 0.5x speed? The image appears to be at half speed, but the audio seems to be at normal speed.

**Comment by SuslikV** [comment]
The recovery process is not perfect, if you got significant difference in track length (look at the text-log during the recovery) then you need to extract raw h264 stream and AAC tracks from the file, multiplex them into .mkv file (with needed fps, etc). And then remux it back to mp4 (with OBS Studio, for example).
