### ISSUE TITLE
Resulting video correct size but way too short

### ISSUE THREAD

**Issue by matthiasg** [SuslikV/untrunc-w#16]
Great tool! But one question:

I tried recovering a video file of about 2.5GB with a exactly identically encoded video of about 51 MB as the correct video.  The correct video is about 3 seconds in length. The resulting, corrected, video is sadly only about 10seconds long even though the resulting size of the video looks correct (2.572.236 kB instead of the corrupted 2.572.229 kB). Both videos were encoded with the exact same parameters, only the length is off.

Is there anything special we would need to do to ensure that the corrected video (which plays back fine just too short) is of the appropriate length ?

ffprobe on the corrected video shows a bitrate of **2003018 kb/s** which is obviously a little high :)

```
D:\Emergency, emergrncy__1999-08-08__\2018-10-23T10_50_32.067+02_00__qweertyuiopasddfgghjjklzxcvbnm!!_\mp4>c:\Development\aeppic\aeppic-server.vt\bin\ffprobe.exe "10_19_2018, 5_01_50 PM.mp4_untrunc.mp4"
ffprobe version 3.2.4 Copyright (c) 2007-2017 the FFmpeg developers
  built with gcc 6.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '10_19_2018, 5_01_50 PM.mp4_untrunc.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 1970-01-01T00:00:42.000000Z
    encoder         : Lavf57.71.100
  Duration: 00:00:10.52, start: 0.000000, bitrate: 2003018 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1920x1080, 113097 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:42.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 64 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:42.000000Z
      handler_name    : SoundHandler
```

**Comment by SuslikV** [comment]
How many samples, %% was recovered reported by the program?

**Comment by matthiasg** [comment]
@SuslikV sorry for responding so slow I did not see your comment. I will create a few broken files in the next few days and have a look. I will also make a few shorter versions and link them from here. 

We always record everything with the exact same settings including audio, but in case of an unexpected process termination it would be really nice to be able to restore the files (even if it took some time)

**Comment by SuslikV** [comment]
If you don't mind, I can try to recover your files, to see what goes wrong during recovery process. Please, find me ("Suslik V") at the https://obsproject.com via private messaging conversation for this.

About the bitrate/size of the file - this is by design, I put the whole contents of the 'moov' box to the recovered file to be able to see where exactly process was stopped and be able to preserve whole data in case of presence of unknown to me streams in the file itself. And of course, if recovery not perfect - it is possible to modify resulting file without significant data loss.

The main goal is to recover the streams that present in the file, to be able to multiplex them later in a new file. Currently, I cannot fully recover the file itself, but can restore its playability (and freely edit it later).

**Comment by matthiasg** [comment]
Thanks for offering to help !

I generated a few shorter videos and there was no issue recovering them, i will try to generate more  diverse test cases to find out when or if it breaks. We did make some changes to the bitrate (Limited it) recently so I have to redo the initial tests. Initially it was just quality limited. I will close this ticket though untiI I can recreate with files I can post.
