### ISSUE TITLE
(Feedback) Works really well!

### ISSUE THREAD

**Issue by ndv400** [SuslikV/untrunc-w#8]
Not an issue, I just thought I'd share. Here's my really old video file that was corrupted way back in May, tried a lot of recovery tools and none could get the job done:
![image](https://user-images.githubusercontent.com/1404955/31008528-26da4e42-a50d-11e7-9f26-68dd0694bbdf.png)
After running it through untrunc-w the audio was restored perfectly! The video is a little bit choppy, though it doesn't matter in this case (as it was just me and a friend of mine talking about some nonsense) and this could possibly be due to me messing up the options part/working file being encoded with different settings:
![vlcsnap-2017-09-29-11h59m12s857](https://user-images.githubusercontent.com/1404955/31008703-b9047040-a50d-11e7-97a4-a90bbe2ec959.png)
Anyway, great job! Keep up the good work :)

**Comment by SuslikV** [comment]
If video frames were skipped during recording and you see that audio track is just fine (usually there is significant difference in track length - info at the end of the recovery), then you can try to extract raw tracks from the recovered file (for example, by DVBPortal MP4Muxer 0.9.3, old soft - do not touch many things at once) and mux this video and audio into mkv format (most programs will use different sync options exactly for mkv muxing; for example, via MeGUI 2308 mkv muxer) and then simply remultiplex it back to mp4 (for example, via OBS Studio).

Find me at https://obsproject.com/forum/  I could try to recover your file if you give me the link to the broken recording via forum's private conversation.

P.S. Thank you for the feedback.

**Comment by SuslikV** [comment]
I have an update for the info you posted. I saw, recently, the same behavior of the recovered file (I mean, almost grey color video in the player). And the sample file had different resolution than broken file. The list of common resolutions (auto-suggestions list) in OBS Studio always the same, so you may try to change this (Settings>Video) make new sample-file and try to recover the broken file again.
