### ISSUE TITLE
untrunc-w.exe - System Error

### ISSUE THREAD

**Issue by jauling** [SuslikV/untrunc-w#9]
Which codec library bundle do I need to satisfy untrunc-w? I'm attempting to use your v1.2 release binary.

There are a few dll's that it cannot find:
avformat-57.dll
avcodec-57.dll
avutil-55.dll

**Comment by SuslikV** [comment]
https://github.com/SuslikV/untrunc-w/tree/deps-folder-content/dependencies_latest
and don't forget _swresample-2.dll_ (internal requirement of one of the libs). Also, the .7z version already bundled with the libs.
